using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace NonProfitFinance.Services;

/// <summary>
/// Service for generating and verifying data integrity checksums for exports.
/// </summary>
public interface IDataIntegrityService
{
    /// <summary>
    /// Generates a checksum/hash for data verification.
    /// </summary>
    string GenerateChecksum(byte[] data);
    
    /// <summary>
    /// Verifies data against a checksum.
    /// </summary>
    bool VerifyChecksum(byte[] data, string checksum);
    
    /// <summary>
    /// Creates a verification block with metadata for export files.
    /// </summary>
    ExportVerificationBlock CreateVerificationBlock(string reportName, int recordCount, decimal? totalAmount, DateTime generatedAt);
    
    /// <summary>
    /// Generates a JSON manifest for backup verification.
    /// </summary>
    string GenerateBackupManifest(BackupManifest manifest);
    
    /// <summary>
    /// Parses and validates a backup manifest.
    /// </summary>
    BackupManifest? ValidateBackupManifest(string manifestJson);
}

public class DataIntegrityService : IDataIntegrityService
{
    public string GenerateChecksum(byte[] data)
    {
        using var sha256 = SHA256.Create();
        var hash = sha256.ComputeHash(data);
        return Convert.ToBase64String(hash);
    }
    
    public bool VerifyChecksum(byte[] data, string checksum)
    {
        var computedChecksum = GenerateChecksum(data);
        return computedChecksum == checksum;
    }
    
    public ExportVerificationBlock CreateVerificationBlock(string reportName, int recordCount, decimal? totalAmount, DateTime generatedAt)
    {
        var block = new ExportVerificationBlock
        {
            ReportName = reportName,
            RecordCount = recordCount,
            TotalAmount = totalAmount,
            GeneratedAt = generatedAt,
            GeneratedBy = Environment.UserName,
            ApplicationVersion = GetApplicationVersion()
        };
        
        // Create verification hash from block data
        var blockData = $"{block.ReportName}|{block.RecordCount}|{block.TotalAmount}|{block.GeneratedAt:O}";
        using var sha256 = SHA256.Create();
        var hash = sha256.ComputeHash(Encoding.UTF8.GetBytes(blockData));
        block.VerificationHash = Convert.ToBase64String(hash)[..12]; // Short hash for display
        
        return block;
    }
    
    public string GenerateBackupManifest(BackupManifest manifest)
    {
        manifest.CreatedAt = DateTime.UtcNow;
        manifest.ApplicationVersion = GetApplicationVersion();
        
        // Calculate checksums for included data
        var options = new JsonSerializerOptions { WriteIndented = true };
        return JsonSerializer.Serialize(manifest, options);
    }
    
    public BackupManifest? ValidateBackupManifest(string manifestJson)
    {
        try
        {
            var manifest = JsonSerializer.Deserialize<BackupManifest>(manifestJson);
            return manifest;
        }
        catch
        {
            return null;
        }
    }
    
    private static string GetApplicationVersion()
    {
        var assembly = System.Reflection.Assembly.GetExecutingAssembly();
        var version = assembly.GetName().Version;
        return version?.ToString() ?? "1.0.0";
    }
}

/// <summary>
/// Verification block included in exported reports.
/// </summary>
public class ExportVerificationBlock
{
    public string ReportName { get; set; } = "";
    public int RecordCount { get; set; }
    public decimal? TotalAmount { get; set; }
    public DateTime GeneratedAt { get; set; }
    public string GeneratedBy { get; set; } = "";
    public string ApplicationVersion { get; set; } = "";
    public string VerificationHash { get; set; } = "";
    
    public string GetFormattedBlock()
    {
        var sb = new StringBuilder();
        sb.AppendLine("═══════════════════════════════════════════════════════");
        sb.AppendLine("                    VERIFICATION BLOCK                   ");
        sb.AppendLine("═══════════════════════════════════════════════════════");
        sb.AppendLine($"  Report: {ReportName}");
        sb.AppendLine($"  Records: {RecordCount:N0}");
        if (TotalAmount.HasValue)
            sb.AppendLine($"  Total Amount: {TotalAmount:C}");
        sb.AppendLine($"  Generated: {GeneratedAt:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"  Generated By: {GeneratedBy}");
        sb.AppendLine($"  App Version: {ApplicationVersion}");
        sb.AppendLine($"  Verification: {VerificationHash}");
        sb.AppendLine("═══════════════════════════════════════════════════════");
        return sb.ToString();
    }
}

/// <summary>
/// Manifest for backup verification and restoration.
/// </summary>
public class BackupManifest
{
    public string BackupType { get; set; } = "Full";
    public DateTime CreatedAt { get; set; }
    public string ApplicationVersion { get; set; } = "";
    public string DatabaseVersion { get; set; } = "";
    public string OrganizationName { get; set; } = "";
    
    // Table counts for verification
    public Dictionary<string, TableManifest> Tables { get; set; } = [];
    
    // Overall statistics
    public BackupStatistics Statistics { get; set; } = new();
    
    // Data checksums
    public string DataChecksum { get; set; } = "";
    public string ManifestChecksum { get; set; } = "";
}

public class TableManifest
{
    public string TableName { get; set; } = "";
    public int RecordCount { get; set; }
    public DateTime? LastModified { get; set; }
    public string DataChecksum { get; set; } = "";
}

public class BackupStatistics
{
    public int TotalTransactions { get; set; }
    public decimal TotalIncome { get; set; }
    public decimal TotalExpenses { get; set; }
    public int TotalCategories { get; set; }
    public int TotalFunds { get; set; }
    public int TotalDonors { get; set; }
    public int TotalGrants { get; set; }
    public int TotalDocuments { get; set; }
    public decimal NetAssets { get; set; }
}
